on: [push]

name: Make distribution

jobs:
  build:
    name: Make distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install Dependencies
        run: poetry install
      - name: Build project
        run: |
          make distribution
      - name: Upload distribution to workflow tab
        uses: actions/upload-artifact@v2
        with:
          name: "distribution"
          path: "dist/*"
