name: Tests

on: [push]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, '3.10']
      max-parallel: 4
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Install Graphviz dependency
        run: sudo apt install graphviz

      - name: Test
        run: |
          make test
          poetry run coverage report -m
